public class Main {
    public static void main (String[] args) {
        System.out.println("Hello world!");
        byte books = 100;
        System.out.println(books);
    short pen = 200;
        System.out.println(pen);
        int pencils = 85;
        System.out.println(pencils);
long ruler = 28;
System.out.println(ruler);
float eraser = 1.5f;
System.out.println(eraser);
double paper = 7.85;
System.out.println(paper);
double things =books+pen+pencils+ruler+eraser+paper;
System.out.println(things);
byte A = 67;
System.out.println(A);
short B = -159;
System.out.println(B);
int C = 569;
System.out.println(C);
long D = 987678965549L;
System.out.println(D);
float K = 27.12F;
System.out.println(K);
double H = 2.786;
System.out.println(H);
int clssA = 23;
int classB = 27;
int classC = 30;
int paperTotal = 480;
int onePupil = 480/(23+27+30);
System.out.println("На каждого ученика рассчитано" + onePupil + "листов!");
int F = 16;
int T1 = 2;
int T0 = 16/2;
int T2 = 20;
int T3 = 1440;
int T4 = 4320;
int T5 = 43200;
System.out.println("За 20 минут работы машина произвела бутылок" +T2*T0+ " штук! ");
System.out.println("За сутки работы машина произвела бутылок" +T3*T0+ " штук! ");
System.out.println("За 3 дня работы машина произвела бутылок" +T4*T0+ " штук! ");
System.out.println("За месяц работы машина произвела бутылок" +T5*T0+ " штук! ");
int totalBank = 120;
int wBank = 2;
int bBank = 4;
int oneClass = wBank+bBank;
int totalClass = totalBank/oneClass;
int totalWbank = totalClass*wBank;
int totalBbank = totalClass*bBank;
System.out.println("В школе, где" + totalClass + "классов!" + "нужно белой краски" + totalWbank +"банок!" + "нужно коричневой краски" + totalBbank + "банок!");
int bananas = 5;
int oneBananas = 80;
int totalBananas = bananas*oneBananas;
int milk = 200;
float oneMilk = 105/100F;
float totalMilk = milk*oneMilk;
int ice = 2;
int oneIce = 100;
int totalIce = ice * oneIce;
int eggs = 4;
int oneEggs = 70;
int totalEggs = eggs *oneEggs;
float mixture = (totalBananas+totalMilk+totalIce+totalEggs)/1000;
System.out.println("Всего" +mixture + "кг!");
int weight = 7;
int gram = 1000;
int weightGr = weight*gram;
System.out.println("надо сбросить"+weightGr+"грамм!");
int oneDayGram = 250;
int anotherDayGram = 500;
int onaDay = weightGr/oneDayGram;
System.out.println("Всего на похудение" + onaDay+ "дней!");
int anotherDay = weightGr/anotherDayGram;
System.out.println("Вего на похудение" + anotherDay+ "дней!");
int year = 12;
int Masha = 67760;
float MashaPlus = Masha*0.1F;
float Masha1 = Masha + MashaPlus;
int MashaYear = Masha*year;
float Masha1Year =Masha1*year;
float rub = Masha1Year - MashaYear;
System.out.println(" У Маши больше на" + rub + "рублей!");
        int Denis = 83690;
        float DenisPlus = Denis*0.1F;
        float Denis1 = Denis + DenisPlus;
        int DenisYear = Denis*year;
        float Denis1Year =Denis1*year;
        float rub1 = Denis1Year - DenisYear;
        System.out.println(" У Дениса больше на" + rub1 + "рублей!");
        int Cris = 76230;
        float CrisPlus = Cris * 0.1F;
        float CrisYear = Cris * year;
        float Cris1 = Cris + CrisPlus;
        float Cris1Year = Cris1 * year;
        float rub3 = Cris1Year - CrisYear;
        System.out.println(" У Кристины больше на" + rub3+ "рублей!");
        float razMasha = Masha1Year/MashaYear;
        System.out.println("Маша будет получать больше в" +razMasha + "раза!");
        float razDenis = Denis1Year/DenisYear;
        System.out.println("Денис будет получать больше в" +razDenis+ "раза!" );
        float razCris = Cris1Year/CrisYear;
        System.out.println("Кристина будет получать больше" +razCris + "раза!");

    }};






